global:
  scrape_interval: 1s # Default is every 1 minute.

scrape_configs:
- job_name: 'demo'
  static_configs:
    - targets:
      - 'demo.promlabs.com:10000'

remote_write:
- url: http://localhost:8081/write

